const github = require('@actions/github')
const { getListComments } = require('./getListComments')
const { setCommitStatus } = require('./setCommitStatus')
const { deleteComments } = require('./deleteComments')
const { generateCommentString } = require('../utils')
const { blue, red } = require('../logger')

exports.setGitComments = async function setGitComments ({ data, token }) {
  const context = github.context
  const octokit = github.getOctokit(token)

  const comments = await getListComments(token)
  await deleteComments(token, comments)

  try {
    blue(`> Creating new comment on commit: ${context.sha}`)

    await octokit.repos.createCommitComment({
      owner: context.repo.owner,
      repo: context.repo.repo,
      commit_sha: context.sha,
      body: `${generateCommentString(data)}
  <p><small><i>Generated by <a href="https://github.com/mazipan/psi-gh-action/" target="_blank" rel="noopenner noreferer">psi-github-action</a></i></small></p>
  <p><small><i><a href="https://github.com/mazipan/psi-gh-action#abbreviation" target="_blank" rel="noopenner noreferer">Learn about the abbreviation</a></i></small></p>
      `
    })
  } catch (error) {
    red(error)
  }

  // status for current commit
  await setCommitStatus(token)
}
