const github = require('@actions/github')
const core = require('@actions/core')
const { getListComments } = require('./getListComments')
const { setCommitStatus } = require('./setCommitStatus')
// const { deleteComments } = require('./deleteComments')
const { generateCommentString } = require('../utils')

exports.setGitComments = async function setGitComments (data, token) {
  const context = github.context
  const octokit = github.getOctokit(token)

  // const comments = await getListComments(token)
  // await deleteComments(token, comments)

  try {
    core.info(`> Creating new comment on commit: ${context.sha}`)

    await octokit.repos.createCommitComment({
      owner: context.repo.owner,
      repo: context.repo.repo,
      commit_sha: context.sha,
      body: `${generateCommentString(data)}

  *Generated by [psi-github-action](https://github.com/mazipan/psi-gh-action/)*
      `
    })
    const comments = await getListComments(token)
    core.info(`${JSON.stringify(comments, null, 2)}`)
  } catch (error) {
    core.info(error)
  }

  // status for current commit
  await setCommitStatus(token)
}
